### ISSUE TITLE
Ascent Path Window

### ISSUE THREAD

**Issue by doubt72** [MuMech/MechJeb2#640]
The ascent path editor window seems to have stopped working in latest build; it comes up as a tiny window that can't be moved or closed (except via the button that opens it from the ascent guidance autopilot window).

It worked very briefly once, but then it bugged out again (this time it was larger, the normal size of the window, but top bar and button were squished down again in the corner) when I used one of the controls in it.  Not sure why, tried poking around in the .cfg files for the craft, but couldn't get it working again (thought maybe the control I used was triggering the issue, but apparently not).

(This is happening on #484 -- not sure when this actually started, since I upgraded from 2.5.1 to the latest to get the fix for a bunch of issues I was having with the autopilot not warping or throttling up for more complicated assembled-in-orbit mothership-lander designs I've been building lately for interplanetary missions.  This version did fix those issues, this is the only issue I've noticed since.)

BTW, love MechJeb, fantastic work on the mod.  And absolutely willing to go in and do any debugging/reproduction necessary if it will help isolate this issue.

**Comment by doubt72** [comment]
More data: seems to work fine on Kerbin launch the couple times I've tried it, but if you switch to a ship (via loaded quicksaves or just switching from the orbit map) in orbit or on a moon (Ike or Minmus so far), it has issues.

**Comment by sarbian** [comment]
This was a stupid mistake on my side when I moved the code from a for to a while. Last dev should fix it

**Comment by doubt72** [comment]
Hmm, there's still an issue with build #489, eventually the ascent path window will glitch (go blank) after launch.  It was always happening after a certain time (1000 seconds after mark or so, seems like, at 16m 41s), so suspect it's related to the new path drawing.  Doesn't matter if it's continuous from launch or if you switch craft (to something that's been flying a while) -- also not sure, but this might have been my original issue all along, but I've certainly noticed the pattern playing today and it's certainly present in the latest build.  It's very consistently correlated with mark time, though.

It also has a super-easy work-around: just reset the mark before the next ascent.  (So no pain on my end -- ironically, poking at this has helped me figure out how to use some of the mechjeb features I wasn't really even aware were there before so...  Good?)

**Comment by doubt72** [comment]
Related?  If you reset a mark before landing, you can also get some weird (but cool) lines in the ascent window.  :D
