### ISSUE TITLE
New Update auto land issue version 2.6.1

### ISSUE THREAD

**Issue by Ksp567** [MuMech/MechJeb2#940]
![kerbal space program screenshot 2017 10 15 - 17 43 34 26](https://user-images.githubusercontent.com/32809619/31582544-31c5e6be-b1d2-11e7-87d4-6456670a07df.png)
Using the land at target feature puts you directly 180 degrees on the other side of the moon/planet. Doesn't matter what planet or moon it is. 
![kerbal space program screenshot 2017 10 15 - 17 43 28 12](https://user-images.githubusercontent.com/32809619/31582542-2cc7fa12-b1d2-11e7-9a18-7766012e12fc.png)

**Comment by bcwinters** [comment]
I have begun noticing issues with MechJeb land at target since the latest KSP update (was working fine previously).

It may be related to this KSP code change:
"CelestialBody GetRelSurfacePosition now calling correct methods."

https://wiki.kerbalspaceprogram.com/wiki/1.3.1

I can see that this method is used to compute the adjustments needed to find the landing spot in at least one place within MechJeb code:
https://github.com/MuMech/MechJeb2/blob/9be3000e57a8140a40831ee3193b9939ab8d9afb/MechJeb2/LandingAutopilot/DeorbitBurn.cs#L46

**Comment by flyright-c172** [comment]
Win10 KSP User. I am using MechJeb2-2.6.1.0 as my only mod. Since the upgrade to KSP V1.3.1.1891 I have had the issue described above. MechJeb still works fine except when trying to use landing guidance from an orbital spacecraft, MechJeb will try to land, unsuccessfully, on opposite side of Mun from the target. Same results at Minmus.
 Results are similar to the screenshots in the original post, though the spacecraft comes in at too high speed and crashes.

**Comment by sarbian** [comment]
It should now be fixed in the dev build. I do not really have the tome to test so you ll have to see for yourself.
Thanks @bcwinters for the 1.3.1 change hint

**Comment by flyright-c172** [comment]
sarbian, Thanks so much for looking at this.
I tested MechJeb Dev #745 landing guidance with a spacecraft orbiting Minmus. It behaves differently, but still not working. Target looks correct, but MechJeb remains in the "Moving to high orbit burn point" status for multiple orbits.
![screenshot370](https://user-images.githubusercontent.com/32875599/31684920-7bac0de0-b33e-11e7-8818-20240877a1da.png)

**Comment by doktorjet** [comment]
Definitely NOT fixed by build 945. Still tries to do correction burn AWAY from target.

**Comment by doc4kidz** [comment]
I installed the update and unfortunately, it did not fix the issue.  Landing Guidance is stuck in the "low deorbit burn" step.  Just keeps orbiting the planet (in my case, Minmus), in time warp mode.  It doesn't crash land now, so I suppose that's an improvement.  Appreciate all efforts to correct this.

**Comment by Ksp567** [comment]
After hours of debugging, I figured out how this happens. Hyper edits Coordinate become un-synced with the actual physical values on the map, sometimes its a small amount, sometimes its 180 degrees out. Easy to fix just remove hyper edit and if someone wants to report that bug to hyper edit page. It seems only effect the longitude coordinates not the latitude.

**Comment by duchenpaul** [comment]
@Ksp567  Good job, but I didn't even install hyperedit, the landing just not working or the accuracy is very poor

**Comment by Ksp567** [comment]
It is still not 100%. But far better, the change log for the update 1.31 mentions streamlining a lot of the code. I guess they changed a lot of the background variables in the code and that is why the calculations are off now. But most of it is above my head. The game is much faster and smoother now but guess this is the cost of those changes.

**Comment by duchenpaul** [comment]
Really? In my case it just keep wrapping without de-orbit burn, seems we still have to wait.
Thank for all those who put efforts on this issue.

**Comment by Phil995511** [comment]
Hello,

Where is it possible to download the new version 2.6.1 #940 or more actualised of your plugin with out landing guidance bug ??

Best regards.

**Comment by duchenpaul** [comment]
It seems works!! Cool!

**Comment by flyright-c172** [comment]
Nice!  MechJeb2-2.6.1.0-747 Dev    Landing Guidance is working for me.
Thanks!

**Comment by doc4kidz** [comment]
Landing guidance is working fine.  Thanks Sarbian (?) for your attention to this matter.
